# Autogenerated! DO NOT EDIT!
# This justfile is autogenerated via https://std.divnix.com/reference/lib/cfg/just.html
# It can be used without Nix by running a locally installed  `just` binary.
# NOTE: Without Nix, you are responsible for having all task dependencies
# available locally!

# devshell env
dev:
    std //example/devshells/default:enter

# get std list
sl:
    std list

# add std in Nix Shell
std:
    nix shell github:divnix/std

# update flake
up:
    nix flake update
